### ISSUE TITLE
static methods and var

### ISSUE THREAD

**Issue by francescoagati** [modjke/mixin#19]
support for static method can be supported adding for example with annotations. marking an instance method of an interface as static 

interface A {
    @:static function sum(a,b) {}
}

**Comment by modjke** [comment]
Well, static can be supported even without additional meta, but back when i've thought about it i could not come up with a use case for that, do you have any practical use-cases?

**Comment by francescoagati** [comment]
for example partials classes. https://github.com/FuzzyWuzzie/haxe-partials
i have used partials for inject some static variables inside a class 
see also example partials log in haxe-partials
```
#if js
@:partials(Log_js)
#elseif cpp
@:partials(Log_cpp)
#end
class Log implements partials.Partial {
    public static function info(msg:String) {
        log("info", msg);
    }

    public static function warn(msg:String) {
        log("warn", msg);
    }

    public static function error(msg:String) {
        throw msg;
    }
}```

**Comment by francescoagati** [comment]
the problem of haxe-partials is that ins't compatible now with haxe 3.4

**Comment by modjke** [comment]
Did not know about haxe-partials, thank you for that link.
I think it's totaly possible to add inlcusion-only (without @base and @overwrite) support for a static fields.
I will look into that.

**Comment by francescoagati** [comment]
thanks also tink_lang have support for partials https://github.com/haxetink/tink_lang

**Comment by modjke** [comment]
Well, after thinking about it for quite a while i still dont think that mixins shoud be used for partial implementation of static methods, after all you just end up with a copies of static field that has no linkage to a class it's been copied to. 
Anyway partial implementation and platform-specific logic decoupling is not the focus of this library

**Comment by francescoagati** [comment]
can be used for metaprogramming for example. when i import static method i
can resolve Types of static method with the locals import in the context
file

2017-11-15 9:32 GMT+01:00 Ignatiev Mikhail <notifications@github.com>:

**Comment by modjke** [comment]
> when i import static method i
> can resolve Types of static method with the locals import in the context
> file

Well, not in this lib, all types in the mixin fields are resolved manually before inclusion.
If you define a mixin field:
```
@mixin function create():SomeClass { /*implementation*/ }
```
it will be resolved to
```
@mixin function create():fully.qualified.package.SomeClass { /*implementation*/ }
```
