### ISSUE TITLE
Haxe for VSCode crashes when using mixins

### ISSUE THREAD

**Issue by bary12** [modjke/mixin#20]
I have some very basic usage of the library, which compiles and runs successfully, but for some reason fails when trying to get completions from the VSCode extension.

mixins/MovingObject.hx
```Haxe
package mixins;

@mixin interface MovingObject {
    public var speed: Int;
}
```

objects/Car.hx
```Haxe
package objects;
import mixins.MovingObject;

class Car implements MovingObject {
    public function isFast(): Boolean {
         return // Here I press Ctrl + Space to get completions
    }
}
```

And the following error message appears in the debug window of the extension:

```
Code: -32603 
/home/bary/haxelib/mixin/0,9,5/lib/mixin/Mixin.hx:229: characters 26-47 : Invalid field access : baseImplements
?:1: characters 1048575-8796094070782 : Called from
Aborted
```
If I add `@baseImplements()` to the mixin, I get a different error

```
 Code: -32603 
/home/bary/haxelib/mixin/0,9,5/lib/mixin/Mixin.hx:89: characters 3-8 : Mixin with mixins.MovingObject already existed...
/home/bary/haxelib/mixin/0,9,5/lib/mixin/Mixin.hx:48: characters 19-32 : Called from
?:1: characters 1-7 : Called from
Aborted
[]
```

**Comment by modjke** [comment]
Will investigate, thanks for the report
Also, what version of haxe and vscode haxe plugin are you using?

**Comment by bary12** [comment]
Seems to be working fine with the latest version of Vshaxe and code on Haxe 3.4.7, can't replicate it.
