### ISSUE TITLE
Cannot return `null` from Void-function

### ISSUE THREAD

**Issue by rcstuber** [modjke/mixin#21]
I want to use Mixins to add (empty) function stubs in case they aren't defined in the base class and to call the base class's implementation if the function is defined there. However this doesn't seem possible, as it will throw this compilation error ``Cannot return `null` from Void-function``. Is there any way around this?
```haxe
@mixin interface SomeMixin {
    @overwrite(addIfAbsent=true) function update():Void {
        $base.update();
    }
}
```

PS: I really like the library so far, very useful!

**Comment by modjke** [comment]
Do you still need this?

**Comment by rcstuber** [comment]
Yes, it would be nice to have this fixed. I also made some minor changes to my local version have it support Haxe 4, I'll see if I can PR them.

**Comment by modjke** [comment]
I've added a test case for this, but it does not seem to throw any errors https://github.com/modjke/mixin/blob/master/test/cases/FunctionNullFromVoidTestCase.hx

You can run tests yourself with `haxe test.hxml`

**Comment by rcstuber** [comment]
Hey, I ran your test case and got the exact same error:

```haxe
test/cases/FunctionNullFromVoidTestCase.hx:34: lines 34-36 : Cannot return `null` from Void-function
test/cases/FunctionNullFromVoidTestCase.hx:27: lines 27-31 : Defined in this class
```

May this be due to you still using Haxe 3? I opened a preliminary PR that adds some fixes to make the lib work with Haxe 4. Since your lib is quite a beast, I don't understand everything you did there, but the changes work fine for me running Haxe version `4.1.4`. Maybe you can test with that and see if you get the same error.

Thanks!

**Comment by modjke** [comment]
Well, yes, i did not account for Haxe 4 support, i will review your PR, big thanks

**Comment by modjke** [comment]
Check this one out https://lib.haxe.org/p/mixin/1.0.0

**Comment by rcstuber** [comment]
Pretty awesome, thanks a lot! The library needs to get more attention, as it's really great.

Btw I figured out why I had wildcard imports in my mixin files, that's because I'm using Haxe's global imports, so currently I'll have to stick with commenting out that check locally.
